# Site settings
title: Android Kotlin 指南
email: your-email@domain.com
description: >
  关于在 Android 上的 Kotlin 开发的官方指南。
baseurl: "/kotlin-guides-cn"
url: "https://msdx.github.io"

# Build settings
markdown: kramdown

collections:
  - changes

plugins:
  - octopress-autoprefixer
  - jekyll-redirect-from

exclude:
  - vendor
